# -*- coding: utf-8 -*-
"""run_A3_DATA5000_T1_2025.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qu-izPrD9L5QSo7KPf81Y__Y3jfxxynK

# Assessment 3 - AI Tools for Business Analytics
### Document Retrieval, Similarity Analysis, and AI-enhanced Search

---
## Assignment Overview
In this notebook, you will implement **AI-driven business analytics** to improve product recommendations in an e-commerce company. You'll explore **vector search, cosine similarity, and LLM-based retrieval** to provide **actionable insights** for stakeholders.

---

NAME:

STUDENT NUMBER:
"""

!pip install unstructured[pdf]

!pip install PyPDF2==3.0.1 pdfplumber==0.10.3 python-docx==1.1.0

# Install required libraries
!pip install -U langchain-community
!pip install ollama
!pip install chromadb

from spacy.cli import download

download("en_core_web_sm")

# Required Libraries
import os
import tempfile
import numpy as np
import pandas as pd
import spacy
import matplotlib.pyplot as plt
import seaborn as sns
from typing import List, Dict, Tuple
import spacy
from langchain.embeddings import HuggingFaceEmbeddings
from langchain.vectorstores import Chroma
from langchain.schema import Document
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain.document_loaders import (
    UnstructuredPDFLoader,
    UnstructuredWordDocumentLoader,
    UnstructuredExcelLoader,
    TextLoader
)
from sentence_transformers import SentenceTransformer
import ollama

"""# Step 1: Initialize a Temporary Directory for ChromaDB"""

CONFIG = {
    'embedding_model': 'sentence-transformers/all-MiniLM-L6-v2',
    'chunk_size': 500,
    'chunk_overlap': 50,
    'similarity_top_k': 5,
    'llm_model': 'llama3.2:latest',
    'temperature': 0.7
}
temp_dir = tempfile.mkdtemp()
print(f"📂 Temporary directory created at: {temp_dir}")

"""# Step 2: Initialize the Embedding Model

"""

try:
    embedding_model = HuggingFaceEmbeddings(
        model_name=CONFIG['embedding_model'],
        model_kwargs={'device': 'cpu'},  # Use 'cuda' if GPU available
        encode_kwargs={'normalize_embeddings': True}
    )
    print("Embedding model initialized successfully!")
except Exception as e:
    print(f"Error initializing embedding model: {e}")
    raise

"""# Step 3: Create ChromaDB Vector Store

"""

try:
    chroma_db = Chroma(
        collection_name="ecommerce_analytics",
        embedding_function=embedding_model,
        persist_directory=temp_dir
    )
    print("ChromaDB vector store created successfully!")
except Exception as e:
    print(f"Error creating ChromaDB: {e}")
    raise

"""
# Step 4: Load Documents from Text and Files"""

import os
from typing import List
from langchain_core.documents import Document
from langchain_community.document_loaders import (
    UnstructuredPDFLoader,
    UnstructuredWordDocumentLoader,
    UnstructuredExcelLoader
)
from langchain.text_splitter import RecursiveCharacterTextSplitter

text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=CONFIG['chunk_size'],
    chunk_overlap=CONFIG['chunk_overlap'],
    length_function=len,
    separators=["\n\n", "\n", " ", ""]
)
# Sample in-memory documents (unchanged) for starting up the memory.
sample_documents = [
    {
        "content": "The iPhone 15 Pro features an A17 Pro chip with 3-nanometer technology, "
                   "titanium build for enhanced durability, and ProMotion display with 120Hz refresh rate. "
                   "Battery life extends up to 29 hours of video playback.",
        "metadata": {"source": "product_catalog", "product": "iPhone 15 Pro", "category": "smartphones"}
    },
    {
        "content": "The Samsung Galaxy S24 Ultra introduces revolutionary AI-powered camera features "
                   "including real-time photo enhancement, object eraser, and generative edit capabilities. "
                   "Features a 200MP main camera sensor and 100x Space Zoom.",
        "metadata": {"source": "product_catalog", "product": "Samsung Galaxy S24 Ultra", "category": "smartphones"}
    },
    {
        "content": "Google Pixel 8 Pro showcases advanced computational photography with Magic Eraser, "
                   "Best Take feature for group photos, and Audio Magic Eraser for videos. "
                   "Powered by Google Tensor G3 chip optimized for AI tasks.",
        "metadata": {"source": "product_catalog", "product": "Google Pixel 8 Pro", "category": "smartphones"}
    }
]

# Convert to Document objects
documents = [
    Document(page_content=doc["content"], metadata=doc["metadata"])
    for doc in sample_documents
]

# General-purpose loader function
def load_external_documents(file_path: str, loader_class) -> List[Document]:
    try:
        if os.path.exists(file_path):
            loader = loader_class(file_path)
            docs = loader.load()
            print(f"Loaded {len(docs)} documents from {file_path}")
            return docs
        else:
            print(f"File not found: {file_path}")
            return []
    except Exception as e:
        print(f"Error loading {file_path}: {e.__class__.__name__}: {e}")
        return []

# Load documents
pdf_documents = load_external_documents("/content/ecommerce_market_report (2).pdf", UnstructuredPDFLoader) #Add in the ecommerce pdf pdf
word_documents = load_external_documents("/content/ecommerce_reviews (2).docx", UnstructuredWordDocumentLoader) #Add in the ecommerce_reviews.docx
excel_documents = load_external_documents("/content/sales_data (1) (1).xlsx", UnstructuredExcelLoader) #add in the sales excel file
# Combine all documents
all_external_docs = pdf_documents + word_documents + excel_documents

# Split external documents into chunks
chunked_external_docs = []
for doc in all_external_docs:
    chunks = text_splitter.split_documents([doc])
    chunked_external_docs.extend(chunks)
all_documents = documents + chunked_external_docs

# Add documents to ChromaDB with IDs for tracking
try:
    doc_ids = [f"doc_{i}" for i in range(len(all_documents))]
    chroma_db.add_documents(all_documents, ids=doc_ids)
    chroma_db.persist()
    print(f" Successfully stored {len(all_documents)} documents in ChromaDB")
except Exception as e:
    print(f" Error storing documents: {e}")

"""
# Step 5: Query ChromaDB for Similar Documents"""

from typing import List
from langchain.schema import Document

def search_similar_documents(query: str, k: int = 5) -> List[Document]:
    """Search for similar documents in ChromaDB."""
    try:
        results = chroma_db.similarity_search_with_score(query, k=k)
        return results
    except Exception as e:
        print(f"Error searching documents: {e}")
        return []

# Refined and expanded list of queries
queries = [
    "What is the price elasticity of demand for premium smartphone models?",
    "Which smartphone features most strongly correlate with high customer satisfaction?",
    "Which geographic region experienced the highest sales growth between Q3 and Q4 2024?",
    "How did the average order value change year-over-year between Q4 2023 and Q4 2024?",
    "What are the main positive and negative sentiment drivers in the customer reviews?"
]

print("\nSIMILARITY SEARCH RESULTS:")
print("=" * 80)

for query in queries:
    print(f"\nQuery: '{query}'")
    print("-" * 40)
    results = search_similar_documents(query, k=3)

    for i, (doc, score) in enumerate(results):
        print(f"\nResult {i+1} (Similarity Score: {1-score:.3f}):")
        print(f"Content: {doc.page_content[:200]}...")
        if doc.metadata:
            print(f"Metadata: {doc.metadata}")

# Tip: load the metadata into a pandas DataFrame for easier analysis of sources and scores.

"""
# Step 6: Compute Cosine Similarity Between Customer Reviews and Product Descriptions"""

try:
    nlp = spacy.load("en_core_web_sm")
    print("\n spaCy model loaded successfully!")
except:
    print("Please install spaCy model: python -m spacy download en_core_web_md")
    raise

# Some of customer reviews for analysis. You can extract more reviews in the word document to get a deeper analysis. Otherwise, this is enough
customer_reviews = {
    "iphone_review_1": "I love the iPhone 15's extended battery life and the titanium build "
                       "feels premium. However, the device feels slightly heavier than expected.",
    "iphone_review_2": "The iPhone 15 Pro delivers top-tier performance, and the 120Hz display is extremely smooth. "
                       "Face ID is fast, but I noticed the phone gets warm during intensive gaming sessions.",
    "iphone_review_3": "While the camera upgrades are impressive, especially in low light, "
                       "I found the transition from my older iPhone a bit underwhelming. Price could be better.",

    "samsung_review_1": "Samsung's AI camera features are absolutely mind-blowing! "
                        "The photo quality is exceptional, but the price point is quite steep.",
    "samsung_review_2": "The S24 Ultra's design is sleek, and the 200MP camera captures incredible detail. "
                        "However, the generative edit features sometimes produce unrealistic results.",
    "samsung_review_3": "I appreciate the big, bright display and long battery life, but the phone is too bulky "
                        "for comfortable one-handed use. Software updates are a bit slow.",

    "pixel_review_1": "Google Pixel's computational photography is unmatched. "
                      "The Magic Eraser works like magic, though I wish the battery lasted longer.",
    "pixel_review_2": "Pixel 8 Pro is excellent for everyday photography, and Android updates arrive quickly. "
                      "Unfortunately, the fingerprint sensor can be unreliable.",
    "pixel_review_3": "Audio Magic Eraser is a useful addition for video recording. "
                      "I wish Google offered more color choices, and the charging speed could be faster."
}


# Product descriptions for comparison. If you can explore the comments for other products, feel free to add them here.
product_descriptions = {
    "iphone_desc":    documents[0].page_content,
    "samsung_desc":   documents[1].page_content,
    "pixel_desc":     documents[2].page_content,
}

def compute_cosine_similarity(vec1: np.ndarray, vec2: np.ndarray) -> float:
    """Compute cosine similarity between two vectors."""
    dot_product = np.dot(vec1, vec2)
    norm_product = np.linalg.norm(vec1) * np.linalg.norm(vec2)
    return dot_product / norm_product if norm_product != 0 else 0

# Create similarity matrix
print("\n COSINE SIMILARITY ANALYSIS:")
print("=" * 80)

similarity_matrix = pd.DataFrame(index=customer_reviews.keys(), columns=product_descriptions.keys())

for review_name, review_text in customer_reviews.items():
    review_vec = nlp(review_text).vector

    for desc_name, desc_text in product_descriptions.items():
        desc_vec = nlp(desc_text).vector
        similarity = compute_cosine_similarity(review_vec, desc_vec)
        similarity_matrix.loc[review_name, desc_name] = similarity

# Display similarity matrix
print("\nSimilarity Matrix (Reviews vs Product Descriptions):")
print(similarity_matrix.round(3))

# Visualize similarity matrix
plt.figure(figsize=(10, 6))
sns.heatmap(similarity_matrix.astype(float), annot=True, cmap='YlOrRd',
            fmt='.3f', cbar_kws={'label': 'Cosine Similarity'})
plt.title('Customer Review - Product Description Similarity Heatmap')
plt.tight_layout()
plt.show()

"""# Step 7: LLM-Powered Retrieval-Augmented Generation (RAG)

## Step 7a: Initialize LLM with Ollama (go to slide of week 10 for further instruction)

**This is compulsory for students using Colab but students with local VSCode can ignore 7a**
"""

!pip install colab-xterm

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# # This script installs Ollama on Linux.
# # It detects the current operating system architecture and installs the appropriate version of Ollama.
# 
# set -eu
# 
# red="$( (/usr/bin/tput bold || :; /usr/bin/tput setaf 1 || :) 2>&-)"
# plain="$( (/usr/bin/tput sgr0 || :) 2>&-)"
# 
# status() { echo ">>> $*" >&2; }
# error() { echo "${red}ERROR:${plain} $*"; exit 1; }
# warning() { echo "${red}WARNING:${plain} $*" >&2; }
# 
# TEMP_DIR=$(mktemp -d)
# cleanup() { rm -rf "$TEMP_DIR"; }
# trap cleanup EXIT
# 
# available() { command -v "$1" >/dev/null; }
# require() {
#     local MISSING=''
#     for TOOL in $*; do
#         if ! available "$TOOL"; then
#             MISSING="$MISSING $TOOL"
#         fi
#     done
# 
#     echo "$MISSING"
# }
# 
# [ "$(uname -s)" = "Linux" ] || error 'This script is intended to run on Linux only.'
# 
# ARCH=$(uname -m)
# case "$ARCH" in
#     x86_64) ARCH="amd64" ;;
#     aarch64|arm64) ARCH="arm64" ;;
#     *) error "Unsupported architecture: $ARCH" ;;
# esac
# 
# IS_WSL2=false
# 
# KERN=$(uname -r)
# case "$KERN" in
#     *icrosoft*WSL2 | *icrosoft*wsl2) IS_WSL2=true;;
#     *microsoft) error "Microsoft WSL1 is not currently supported. Please use WSL2 with 'wsl --set-version <distro> 2'" ;;
#     *) ;;
# esac
# 
# VER_PARAM="${OLLAMA_VERSION:+?version=$OLLAMA_VERSION}"
# 
# SUDO=
# if [ "$(id -u)" -ne 0 ]; then
#     # Running as root, no need for sudo
#     if ! available sudo; then
#         error "This script requires superuser permissions. Please re-run as root."
#     fi
# 
#     SUDO="sudo"
# fi
# 
# NEEDS=$(require curl awk grep sed tee xargs)
# if [ -n "$NEEDS" ]; then
#     status "ERROR: The following tools are required but missing:"
#     for NEED in $NEEDS; do
#         echo "  - $NEED" >&2
#     done
#     exit 1
# fi
# 
# for BINDIR in /usr/local/bin /usr/bin /bin; do
#     echo "$PATH" | grep -q "$BINDIR" && break || continue
# done
# OLLAMA_INSTALL_DIR=$(dirname "${BINDIR}")
# 
# if [ -d "$OLLAMA_INSTALL_DIR/lib/ollama" ] ; then
#     status "Cleaning up old version at $OLLAMA_INSTALL_DIR/lib/ollama"
#     $SUDO rm -rf "$OLLAMA_INSTALL_DIR/lib/ollama"
# fi
# status "Installing ollama to $OLLAMA_INSTALL_DIR"
# $SUDO install -o0 -g0 -m755 -d "$BINDIR"
# $SUDO install -o0 -g0 -m755 -d "$OLLAMA_INSTALL_DIR/lib/ollama"
# status "Downloading Linux ${ARCH} bundle"
# curl --fail --show-error --location --progress-bar \
#     "https://ollama.com/download/ollama-linux-${ARCH}.tgz${VER_PARAM}" | \
#     $SUDO tar -xzf - -C "$OLLAMA_INSTALL_DIR"
# 
# if [ "$OLLAMA_INSTALL_DIR/bin/ollama" != "$BINDIR/ollama" ] ; then
#     status "Making ollama accessible in the PATH in $BINDIR"
#     $SUDO ln -sf "$OLLAMA_INSTALL_DIR/ollama" "$BINDIR/ollama"
# fi
# 
# # Check for NVIDIA JetPack systems with additional downloads
# if [ -f /etc/nv_tegra_release ] ; then
#     if grep R36 /etc/nv_tegra_release > /dev/null ; then
#         status "Downloading JetPack 6 components"
#         curl --fail --show-error --location --progress-bar \
#             "https://ollama.com/download/ollama-linux-${ARCH}-jetpack6.tgz${VER_PARAM}" | \
#             $SUDO tar -xzf - -C "$OLLAMA_INSTALL_DIR"
#     elif grep R35 /etc/nv_tegra_release > /dev/null ; then
#         status "Downloading JetPack 5 components"
#         curl --fail --show-error --location --progress-bar \
#             "https://ollama.com/download/ollama-linux-${ARCH}-jetpack5.tgz${VER_PARAM}" | \
#             $SUDO tar -xzf - -C "$OLLAMA_INSTALL_DIR"
#     else
#         warning "Unsupported JetPack version detected.  GPU may not be supported"
#     fi
# fi
# 
# install_success() {
#     status 'The Ollama API is now available at 127.0.0.1:11434.'
#     status 'Install complete. Run "ollama" from the command line.'
# }
# trap install_success EXIT
# 
# # Everything from this point onwards is optional.
# 
# configure_systemd() {
#     if ! id ollama >/dev/null 2>&1; then
#         status "Creating ollama user..."
#         $SUDO useradd -r -s /bin/false -U -m -d /usr/share/ollama ollama
#     fi
#     if getent group render >/dev/null 2>&1; then
#         status "Adding ollama user to render group..."
#         $SUDO usermod -a -G render ollama
#     fi
#     if getent group video >/dev/null 2>&1; then
#         status "Adding ollama user to video group..."
#         $SUDO usermod -a -G video ollama
#     fi
# 
#     status "Adding current user to ollama group..."
#     $SUDO usermod -a -G ollama "$(whoami)"
# 
#     status "Creating ollama systemd service..."
#     cat <<EOF | $SUDO tee /etc/systemd/system/ollama.service >/dev/null
# [Unit]
# Description=Ollama Service
# After=network-online.target
# 
# [Service]
# ExecStart=$BINDIR/ollama serve
# User=ollama
# Group=ollama
# Restart=always
# RestartSec=3
# Environment="PATH=$PATH"
# 
# [Install]
# WantedBy=default.target
# EOF
#     SYSTEMCTL_RUNNING="$(systemctl is-system-running || true)"
#     case $SYSTEMCTL_RUNNING in
#         running|degraded)
#             status "Enabling and starting ollama service..."
#             $SUDO systemctl daemon-reload
#             $SUDO systemctl enable ollama
# 
#             start_service() { $SUDO systemctl restart ollama; }
#             trap start_service EXIT
#             ;;
#         *)
#             warning "systemd is not running"
#             if [ "$IS_WSL2" = true ]; then
#                 warning "see https://learn.microsoft.com/en-us/windows/wsl/systemd#how-to-enable-systemd to enable it"
#             fi
#             ;;
#     esac
# }
# 
# if available systemctl; then
#     configure_systemd
# fi
# 
# # WSL2 only supports GPUs via nvidia passthrough
# # so check for nvidia-smi to determine if GPU is available
# if [ "$IS_WSL2" = true ]; then
#     if available nvidia-smi && [ -n "$(nvidia-smi | grep -o "CUDA Version: [0-9]*\.[0-9]*")" ]; then
#         status "Nvidia GPU detected."
#     fi
#     install_success
#     exit 0
# fi
# 
# # Don't attempt to install drivers on Jetson systems
# if [ -f /etc/nv_tegra_release ] ; then
#     status "NVIDIA JetPack ready."
#     install_success
#     exit 0
# fi
# 
# # Install GPU dependencies on Linux
# if ! available lspci && ! available lshw; then
#     warning "Unable to detect NVIDIA/AMD GPU. Install lspci or lshw to automatically detect and install GPU dependencies."
#     exit 0
# fi
# 
# check_gpu() {
#     # Look for devices based on vendor ID for NVIDIA and AMD
#     case $1 in
#         lspci)
#             case $2 in
#                 nvidia) available lspci && lspci -d '10de:' | grep -q 'NVIDIA' || return 1 ;;
#                 amdgpu) available lspci && lspci -d '1002:' | grep -q 'AMD' || return 1 ;;
#             esac ;;
#         lshw)
#             case $2 in
#                 nvidia) available lshw && $SUDO lshw -c display -numeric -disable network | grep -q 'vendor: .* \[10DE\]' || return 1 ;;
#                 amdgpu) available lshw && $SUDO lshw -c display -numeric -disable network | grep -q 'vendor: .* \[1002\]' || return 1 ;;
#             esac ;;
#         nvidia-smi) available nvidia-smi || return 1 ;;
#     esac
# }
# 
# if check_gpu nvidia-smi; then
#     status "NVIDIA GPU installed."
#     exit 0
# fi
# 
# if ! check_gpu lspci nvidia && ! check_gpu lshw nvidia && ! check_gpu lspci amdgpu && ! check_gpu lshw amdgpu; then
#     install_success
#     warning "No NVIDIA/AMD GPU detected. Ollama will run in CPU-only mode."
#     exit 0
# fi
# 
# if check_gpu lspci amdgpu || check_gpu lshw amdgpu; then
#     status "Downloading Linux ROCm ${ARCH} bundle"
#     curl --fail --show-error --location --progress-bar \
#         "https://ollama.com/download/ollama-linux-${ARCH}-rocm.tgz${VER_PARAM}" | \
#         $SUDO tar -xzf - -C "$OLLAMA_INSTALL_DIR"
# 
#     install_success
#     status "AMD GPU ready."
#     exit 0
# fi
# 
# CUDA_REPO_ERR_MSG="NVIDIA GPU detected, but your OS and Architecture are not supported by NVIDIA.  Please install the CUDA driver manually https://docs.nvidia.com/cuda/cuda-installation-guide-linux/"
# # ref: https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#rhel-7-centos-7
# # ref: https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#rhel-8-rocky-8
# # ref: https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#rhel-9-rocky-9
# # ref: https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#fedora
# install_cuda_driver_yum() {
#     status 'Installing NVIDIA repository...'
# 
#     case $PACKAGE_MANAGER in
#         yum)
#             $SUDO "$PACKAGE_MANAGER" -y install yum-utils
#             if curl -I --silent --fail --location "https://developer.download.nvidia.com/compute/cuda/repos/$1$2/$(uname -m | sed -e 's/aarch64/sbsa/')/cuda-$1$2.repo" >/dev/null ; then
#                 $SUDO "$PACKAGE_MANAGER"-config-manager --add-repo https://developer.download.nvidia.com/compute/cuda/repos/$1$2/$(uname -m | sed -e 's/aarch64/sbsa/')/cuda-$1$2.repo
#             else
#                 error "$CUDA_REPO_ERR_MSG"
#             fi
#             ;;
#         dnf)
#             if curl -I --silent --fail --location "https://developer.download.nvidia.com/compute/cuda/repos/$1$2/$(uname -m | sed -e 's/aarch64/sbsa/')/cuda-$1$2.repo" >/dev/null ; then
#                 $SUDO "$PACKAGE_MANAGER" config-manager --add-repo https://developer.download.nvidia.com/compute/cuda/repos/$1$2/$(uname -m | sed -e 's/aarch64/sbsa/')/cuda-$1$2.repo
#             else
#                 error "$CUDA_REPO_ERR_MSG"
#             fi
#             ;;
#     esac
# 
#     case $1 in
#         rhel)
#             status 'Installing EPEL repository...'
#             # EPEL is required for third-party dependencies such as dkms and libvdpau
#             $SUDO "$PACKAGE_MANAGER" -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-$2.noarch.rpm || true
#             ;;
#     esac
# 
#     status 'Installing CUDA driver...'
# 
#     if [ "$1" = 'centos' ] || [ "$1$2" = 'rhel7' ]; then
#         $SUDO "$PACKAGE_MANAGER" -y install nvidia-driver-latest-dkms
#     fi
# 
#     $SUDO "$PACKAGE_MANAGER" -y install cuda-drivers
# }
# 
# # ref: https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#ubuntu
# # ref: https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#debian
# install_cuda_driver_apt() {
#     status 'Installing NVIDIA repository...'
#     if curl -I --silent --fail --location "https://developer.download.nvidia.com/compute/cuda/repos/$1$2/$(uname -m | sed -e 's/aarch64/sbsa/')/cuda-keyring_1.1-1_all.deb" >/dev/null ; then
#         curl -fsSL -o "$TEMP_DIR"/cuda-keyring.deb https://developer.download.nvidia.com/compute/cuda/repos/$1$2/$(uname -m | sed -e 's/aarch64/sbsa/')/cuda-keyring_1.1-1_all.deb
#     else
#         error "$CUDA_REPO_ERR_MSG"
#     fi
# 
#     case $1 in
#         debian)
#             status 'Enabling contrib sources...'
#             $SUDO sed 's/main/contrib/' < /etc/apt/sources.list | $SUDO tee /etc/apt/sources.list.d/contrib.list > /dev/null
#             if [ -f "/etc/apt/sources.list.d/debian.sources" ]; then
#                 $SUDO sed 's/main/contrib/' < /etc/apt/sources.list.d/debian.sources | $SUDO tee /etc/apt/sources.list.d/contrib.sources > /dev/null
#             fi
#             ;;
#     esac
# 
#     status 'Installing CUDA driver...'
#     $SUDO dpkg -i "$TEMP_DIR"/cuda-keyring.deb
#     $SUDO apt-get update
# 
#     [ -n "$SUDO" ] && SUDO_E="$SUDO -E" || SUDO_E=
#     DEBIAN_FRONTEND=noninteractive "$SUDO_E" apt-get -y install cuda-drivers -q
# }
# 
# if [ ! -f "/etc/os-release" ]; then
#     error "Unknown distribution. Skipping CUDA installation."
# fi
# 
# . /etc/os-release
# 
# OS_NAME=$ID
# OS_VERSION=$VERSION_ID
# 
# PACKAGE_MANAGER=
# for PACKAGE_MANAGER in dnf yum apt-get; do
#     if available "$PACKAGE_MANAGER"; then
#         break
#     fi
# done
# 
# if [ -z "$PACKAGE_MANAGER" ]; then
#     error "Unknown package manager. Skipping CUDA installation."
# fi
# 
# if ! check_gpu nvidia-smi || [ -z "$(nvidia-smi | grep -o "CUDA Version: [0-9]*\.[0-9]*")" ]; then
#     case $OS_NAME in
#         centos|rhel) install_cuda_driver_yum 'rhel' $(echo "$OS_VERSION" | cut -d '.' -f 1) ;;
#         rocky) install_cuda_driver_yum 'rhel' $(echo "$OS_VERSION" | cut -c1) ;;
#         fedora) [ "$OS_VERSION" -lt '39' ] && install_cuda_driver_yum "$OS_NAME" "$OS_VERSION" || install_cuda_driver_yum "$OS_NAME" '39';;
#         amzn) install_cuda_driver_yum 'fedora' '37' ;;
#         debian) install_cuda_driver_apt "$OS_NAME" "$OS_VERSION" ;;
#         ubuntu) install_cuda_driver_apt "$OS_NAME" $(echo "$OS_VERSION" | sed 's/\.//') ;;
#         *) exit ;;
#     esac
# fi
# 
# if ! lsmod | grep -q nvidia || ! lsmod | grep -q nvidia_uvm; then
#     KERNEL_RELEASE="$(uname -r)"
#     case $OS_NAME in
#         rocky) $SUDO "$PACKAGE_MANAGER" -y install kernel-devel kernel-headers ;;
#         centos|rhel|amzn) $SUDO "$PACKAGE_MANAGER" -y install kernel-devel-"$KERNEL_RELEASE" kernel-headers-"$KERNEL_RELEASE" ;;
#         fedora) $SUDO "$PACKAGE_MANAGER" -y install kernel-devel-"$KERNEL_RELEASE" ;;
#         debian|ubuntu) $SUDO apt-get -y install linux-headers-"$KERNEL_RELEASE" ;;
#         *) exit ;;
#     esac
# 
#     NVIDIA_CUDA_VERSION=$($SUDO dkms status | awk -F: '/added/ { print $1 }')
#     if [ -n "$NVIDIA_CUDA_VERSION" ]; then
#         $SUDO dkms install "$NVIDIA_CUDA_VERSION"
#     fi
# 
#     if lsmod | grep -q nouveau; then
#         status 'Reboot to complete NVIDIA CUDA driver install.'
#         exit 0
#     fi
# 
#     $SUDO modprobe nvidia
#     $SUDO modprobe nvidia_uvm
# fi
# 
# # make sure the NVIDIA modules are loaded on boot with nvidia-persistenced
# if available nvidia-persistenced; then
#     $SUDO touch /etc/modules-load.d/nvidia.conf
#     MODULES="nvidia nvidia-uvm"
#     for MODULE in $MODULES; do
#         if ! grep -qxF "$MODULE" /etc/modules-load.d/nvidia.conf; then
#             echo "$MODULE" | $SUDO tee -a /etc/modules-load.d/nvidia.conf > /dev/null
#         fi
#     done
# fi
# 
# status "NVIDIA GPU ready."
# install_success

# Commented out IPython magic to ensure Python compatibility.
# %load_ext colabxterm
# %xterm

# READ THIS: TYPE IN Following step by step code in the terminal below:
#-------------Step 1-------------------------
# curl https://ollama.ai/install.sh | sh
#-------------Step 2-------------------------
# ollama serve
#-------------Step 3-------------------------
# RUN THIS CELL AGAIN, otherwise you cannot do the step 4 to download llama3.2
#-------------Step 4-------------------------
# ollama run llama3.2

# Commented out IPython magic to ensure Python compatibility.
# %reload_ext colabxterm
# %xterm

# READ THIS: TYPE IN Following step by step code in the terminal below:
#-------------Step 1-------------------------
# curl https://ollama.ai/install.sh | sh
#-------------Step 2-------------------------
# ollama serve
#-------------Step 3-------------------------
# RUN THIS CELL AGAIN, otherwise you cannot do the step 4 to download llama3.2
#-------------Step 4-------------------------
# ollama run llama3.2

# Check if you downloaded the model, it should display llama3.2:latest
!ollama list

"""## Step 7b: Run a RAG Model"""

import ollama

class BusinessRAGSystem:

    def __init__(self, vector_store, llm_model='llama3.2:latest'):  # Put in the name of the LLM model from the ollama list above
        self.vector_store = vector_store
        self.llm_model = llm_model

    def retrieve_context(self, query: str, k: int = 5) -> str:

        results = self.vector_store.similarity_search(query, k=k)
        context = "\n\n".join([f"Document {i+1}: {doc.page_content}"
                              for i, doc in enumerate(results)])
        return context

    def generate_response(self, query: str, context: str,
                         business_context: str = "") -> str:
        """Generate LLM response with retrieved context."""

        system_prompt = """You are an AI business analyst specializing in e-commerce
        and product analytics. Provide data-driven insights and actionable recommendations
        based on the provided context. Focus on business value and strategic implications."""

        user_prompt = f"""
        Business Context: {business_context}

        Retrieved Information:
        {context}

        User Query: {query}

        Please provide a comprehensive analysis with:
        1. Key findings from the data
        2. Business implications
        3. Actionable recommendations
        4. Potential risks or considerations
        """
        try:
            response = ollama.generate(
                model=self.llm_model,
                prompt=f"{system_prompt}\n\n{user_prompt}",
                options={
                    'temperature': CONFIG['temperature'],
                    'max_tokens': 50
                }
            )
            return response['response']
        except Exception as e:
            return f"Error generating response: {e}. Please ensure Ollama is running."

rag_system = BusinessRAGSystem(chroma_db)

# Business analysis queries. For your assessment report writing, you can attempt with other analysis questions here
business_queries = [
    {
        "query": "What smartphone features drive customer satisfaction based on reviews?",
        "context": "Q4 2024 smartphone market analysis"
    },
    {
         "query": "How can we improve our product recommendation system using AI insights?",
         "context": "E-commerce conversion rate: 2.3%, Average cart value: $450"
    },
    {
         "query": "What pricing strategies should we consider for premium smartphones?",
         "context": "Target market: Tech enthusiasts, age 25-45, household income >$75k"
    }
]

print("\n RAG-POWERED BUSINESS ANALYSIS:")
print("=" * 80)

for bq in business_queries:
    print(f"\n Analysis Query: {bq['query']}")
    print(f" Business Context: {bq['context']}")
    print("-" * 80)

    context = rag_system.retrieve_context(bq['query'])

    # Generate response
    response = rag_system.generate_response(
        bq['query'],
        context,
        bq['context']
    )

    print(f"AI Analysis:\n{response}")